### ISSUE TITLE
Error: Cannot find module '...render2katex/index.js'

### ISSUE THREAD

**Issue by hyOzd** [ProfFan/phabritex#1]
I've tried installing this on my phabricator installation but I'm getting below error in the preview area:

`Execution of`render2katex`failed (#8), check your syntax: module.js:340 throw err; ^ Error: Cannot find module '/root/render2katex/index.js' at Function.Module._resolveFilename (module.js:338:15) at Function.Module._load (module.js:280:25) at Function.Module.runMain (module.js:497:10) at startup (node.js:119:16) at node.js:902:3`

It seems that phabricator cannot find the `index.js` file. But I can successfully run the command:

```
nodejs /root/render2katex/index.js
```

So, the file is there. But it's somehow inaccessible to the phabricator (daemons?). What can I do?

**Comment by hyOzd** [comment]
I'm sorry. Turns out it was my mistake. I shouldn't have installed render2katex under `/root/` directory which is inaccessible to other users (drwx------). When I moved it under the `/var/` directory, it worked without problems.

By the way, thanks a lot for your work!

**Comment by ProfFan** [comment]
Really nice to see that you like it :)
