### ISSUE TITLE
node: command not found

### ISSUE THREAD

**Issue by airlsyn** [ProfFan/phabritex#2]
Execution of `render2katex` failed (#127), check your syntax: sh: node: command not found

However, in terminal `node -v` returns `v4.4.3`

Any help will be highly appreciated.

**Comment by ProfFan** [comment]
Should be a PATH issue. Put your node executable directory `which node` in your global `PATH` (Not `~/.profile` as it is only for one user.

**Comment by airlsyn** [comment]
Sure, I have put it in `/etc/profile`, the error still exist. Even if change `node` in `katexinline.php` and `render2katex.php` to `/bin/node` (which node), I get the same error again.

**Comment by airlsyn** [comment]
Finally, I fixed this problem.
- alway be the exception `sh: node: command not found` was caused by the cache of `Ph`, using `bin/cache purge --purge-all` to clean the cache, one can get the correct exception
- another is the enabled Selinux, so disable it.

**Comment by ProfFan** [comment]
Well I got it. SELinux prevents php from executing the node executable.

**Comment by ProfFan** [comment]
By the way, thank you for reporting, I will soon fix the docs. :)
