### ISSUE TITLE
aligned environment needed

### ISSUE THREAD

**Issue by Zarrathustra** [ProfFan/phabritex#3]
Hi, I love your work.

Currently, we use phabritex well in our phabricator system. However, we are eager to use `aligned` environment in katex. Best to my knowledge, `aligned` environment is supported until katex 0.6.0.

So, what is your version of katex in this repo? It is possible to support `aligned` environment.

Best wishes!

Mingxu

**Comment by ProfFan** [comment]
Thanks for the appreciation! It should be quite straightforward to upgrade the version of katex as it is only a matter of replacing one js and one css file. If you are not comfortable with that I can find some time to upgrade it in the following weeks.

**Comment by ProfFan** [comment]
btw, version is 0.5.1, so an upgrade is required.

**Comment by Zarrathustra** [comment]
Thank you.

I have change the dependency of katex in `render2katex/package.json` to 0.6.0 and then re-install `render2katex`.

Now, aligned environment is available.

Hope you may upgrade the dependency of katex in your source code, so more people will benefit from it.

Best wishes.

Mingxu

**Comment by ProfFan** [comment]
I've upgraded the dependency in `render2katex`. Thanks for the feedback and happy hacking :)
